name: Create package

on: [workflow_dispatch]

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          mkdir staging && cp */target/conduit-*.{jar,zip} staging

      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: staging

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: staging/*.zip
