name: Create package

on: [workflow_dispatch]

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with all history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Checkout out the latest tagged commit
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.latesttag.outputs.tag }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          mkdir ~/staging && cp -r . ~/staging

      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: ~/staging

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r conduit-artifact.zip ~/staging

      - name: Create zip artifact for project
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latesttag.outputs.tag }}
          files: conduit-artifact.zip
