name: Create release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - "!.github/**"
      - "!**/*.yaml"
# if it's not ci skip, it'll trigger maven release, which will bump the version

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout out repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Create Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          maven-args: "-DskipTests"
          version-minor: true
          skip-perform: true
          git-release-bot-name: "maven-release"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Invoke workflow without inputs
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: package.yaml
#          token: ${{ secrets.ACTION_PAT }}